# Generated by Django 5.1 on 2024-08-23 12:29

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('Mob', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Email', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('adhaar', models.CharField(blank=True, max_length=16, null=True)),
                ('reset_token', models.CharField(blank=True, max_length=100, null=True)),
                ('avtar', models.ImageField(default='avtar/avtar.png', upload_to='avtar/')),
                ('user_category', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('latlong', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, unique=True)),
                ('sub_location', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, unique=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('telegram_group_id', models.CharField(blank=True, max_length=100, null=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
