# Generated by Django 5.1.1 on 2024-09-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pond',
            name='mob_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
