# Generated by Django 5.1.1 on 2024-09-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pond_mob_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pond',
            name='mob_no',
        ),
    ]
