# Generated by Django 5.0.6 on 2024-08-27 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_pond_sub_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('Mob', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Email', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.admin'),
            preserve_default=False,
        ),
    ]
