# Generated by Django 5.0.6 on 2024-08-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_admin_user_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='avtar',
            field=models.ImageField(default='avtar/avtar.png', upload_to='avtar/'),
        ),
    ]
