# Generated by Django 5.0.6 on 2024-08-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_user_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avtar',
            field=models.ImageField(blank=True, null=True, upload_to='avtar/'),
        ),
    ]
